version: '3.8'

services:
  worker:
    build:
      context: ../apps/worker
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_ORIGINS=*
    restart: always
